os:
  - Visual Studio 2015

configuration:
  - Release

platform:
  - Win32
  
install:
  - vcpkg install freetype
  
cache:
  - c:\tools\vcpkg\installed\  

before_build:
  - cmake -G "Visual Studio 14 2015" -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake

build:
  project: fontbm.sln
  
after_build:
 - 7z a fontbm.zip "./Release/*" "-x!unit_tests.exe"

artifacts:
  - path: fontbm.zip
    name: fontbm

deploy:
  provider: GitHub
  description: 'fontbm windows binaries'
  auth_token:
    secure: NmZvjeSjyBO6deqSmYnOk2QHPDm4/IQ6Aup8OozhGMhOmIa8xvaC5IM+y+21kkvG
  artifact: fontbm
  on:
    appveyor_repo_tag: true
