#!/bin/bash
WORKING_DIR=$(dirname $0)
if [ "$(uname)" == "Darwin" ]; then
    NODE_PATH=$WORKING_DIR/tools/node/mac64/bin/node
else
    NODE_PATH=$WORKING_DIR/tools/node/win64/node.exe
fi

# 8192MB of max memory instead of default 1400 to allow to convert projects with a lot of assets.
PROJECT_PATH=${PROJECT_PATH:-`pwd`/..} $NODE_PATH --max-old-space-size=8192 $WORKING_DIR/pipeline/node_modules/jake/bin/cli.js -f $WORKING_DIR/pipeline/Jakefile.js $1 $2 $3 $4 $5
